name: Bug Report
description: Report a reproducible bug.
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version or commit
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
    validations:
      required: false
