name: SBOM

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "59 4 * * 4"

permissions:
  contents: read

jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom.spdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx-json
          path: sbom.spdx.json
