name: SemVer

on:
  pull_request:
    paths:
      - "crates/**"
      - "Cargo.toml"
      - "Cargo.lock"

permissions:
  contents: read

jobs:
  cargo-semver-checks:
    name: cargo-semver-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          exclude: pqcb-backend-rustcrypto
          baseline-rev: ${{ github.event.pull_request.base.sha }}
